# Site settings
title: Joe Izzard
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joe Izzard
user_description: I'm a theatrical lighting programmer, with a love for software and electronics.
user_title: Lighting Programmer & General Geek
email: joe@izzard.me
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

social-networks:
  email:
    address: Joe@Izzard.me
    enable:
      homepage: true
      contact: true
  facebook:
    username: JoeIzzard
    enable:
      homepage: false
      contact: false
  twitter:
    username: JoeIzzard
    enable:
      homepage: true
      contact: true
  instagram:
    username: JoeIzzard
    enable:
      homepage: true
      contact: true
  youtube:
    username: JoeIzzard
    enable:
      homepage: false
      contact: false
  snapchat:
    username: JoeIzzard
    enable:
      homepage: false
      contact: false
  reddit:
    username: JoeIzzard
    enable:
      homepage: false
      contact: false
  stackoverflow:
    url: JoeIzzard
    enable:
      homepage: false
      contact: false
  linkedin:
    username: JoeIzzard
    enable:
      homepage: false
      contact: false
  website:
    url: https://joe.izzard.me
    enable:
      homepage: true
      contact: true
  phone:
    number: 98765432
    enable:
      homepage: false
      contact: false
  whatsapp:
    number: 12345678
    enable:
      homepage: false
      contact: false
  vcard:
    url: JoeIzzard
    enable:
      homepage: false
      contact: false



# Google-analytics
google-analytics:
  id: "UA-167108707-1"

exclude: ['package.json', 'src' , 'node_modules']
